// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv4X_UQMxnEQL5LLG0FqU5TSVIds8dwJI',
    appId: '1:1003974979728:web:3ce856c80b1f8fa5c32815',
    messagingSenderId: '1003974979728',
    projectId: 'app-nest-990e5',
    authDomain: 'app-nest-990e5.firebaseapp.com',
    storageBucket: 'app-nest-990e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6MOtNUuLazfFezOeY3VkZefvaMRMdpqc',
    appId: '1:1003974979728:android:ed1738fc2705be83c32815',
    messagingSenderId: '1003974979728',
    projectId: 'app-nest-990e5',
    storageBucket: 'app-nest-990e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKSSPgFZCDOvNch---cLI8xMid_mNb4NQ',
    appId: '1:1003974979728:ios:6513737f4ec34eb0c32815',
    messagingSenderId: '1003974979728',
    projectId: 'app-nest-990e5',
    storageBucket: 'app-nest-990e5.appspot.com',
    iosClientId:
        '1003974979728-7rusr3l7svvb5nf0p0m94iviu9t8r9av.apps.googleusercontent.com',
    iosBundleId: 'com.therhenals.vial',
  );
}
